language: rust

# TODO(sirver): support beta, stable
rust:
  - nightly

install:
  - pip install 'Sphinx' --user
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

# TODO(sirver): build & publish docs somewhere.
script:
  - ./travis_test.sh

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUST_BACKTRACE=1
