[package]
name = "switchboard"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies]
serde = "0.4.3"
serde_macros = "0.4.3"
uuid = "0.1"

[dependencies.mio]
git="https://github.com/carllerche/mio.git"
