[package]
name = "switchboard"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies]
serde = "0.4.3"
serde_macros = "0.4.3"
uuid = "0.1"

[dependencies.mio]
git="https://github.com/carllerche/mio.git"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib.git"

[dependencies.gtk]
git = "https://github.com/rust-gnome/gtk.git"
features = ["gtk_3_12"]

[dependencies.cairo-rs]
git = "https://github.com/rust-gnome/cairo.git"

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox.git"
