[package]
name = "swiboe"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies]
clap = "1.2.0"
libc = "0.1.8"
serde = "0.5.2"
serde_json = "0.5.1"
serde_macros = "0.5.1"
tempdir = "0.3.4"
thread-scoped = "1.0.1"
threadpool = "0.1.4"
time = "0.1.32"
uuid = "0.1"

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"
rev = "fcec179737411ac105f8b27d38cb7ceee8c5c5d7"

[[test]]
name = "tests"

[[bench]]
name = "benches"
