[package]
name = "switchboard_gtk_gui"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies.glib]
git = "https://github.com/rust-gnome/glib.git"

[dependencies.gtk]
git = "https://github.com/rust-gnome/gtk.git"
features = ["gtk_3_12"]

[dependencies.cairo-rs]
git = "https://github.com/rust-gnome/cairo.git"

[dependencies.switchboard]
path = ".."
