[package]
rustbox = "*"
name = "term_gui"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
time = "*"
uuid = "0.1"
rustbox = "*"

[dependencies.switchboard]
path = ".."

