[package]
rustbox = "*"
name = "term_gui"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies]
serde = "0.5.1"
serde_json = "0.5.1"
serde_macros = "0.5.1"
time = "*"
uuid = "0.1"
rustbox = "*"

[dependencies.switchboard]
path = ".."

